### ISSUE TITLE
Cant start container

### ISSUE THREAD

**Issue by EstebanBosse** [lenartj/labview#2]
When I run docker `build -t lenart/labview .` an error ocurred:
```
Sending build context to Docker daemon  96.76MB
Step 1/6 : FROM debian:jessie
 ---> 86baf4e8cde9
Step 2/6 : MAINTAINER Janos Lenart <janos@lenart.io>
 ---> Using cache
 ---> cdd67c1f2763
Step 3/6 : COPY labviewlinux.zip spd_readdir.c labview.sh entrypoint.sh /
 ---> Using cache
 ---> 3225e75efa23
Step 4/6 : RUN sed -i 's/httpredir.debian.org/deb.debian.org/' -i /etc/apt/sources.list  && dpkg --add-architecture i386  && apt-get update  && apt-get install -y       unzip alien gcc-multilib libx11-6 libx11-6:i386 libxext6:i386  && cd /tmp  && unzip /labviewlinux.zip  && alien -i --target=amd64 LabVIEW61Linux/*.rpm  && rm -rf /tmp/LabVIEW61Linux  && gcc -o spd_readdir.so -fPIC -march=i586 -m32 -shared /spd_readdir.c -ldl  && apt-get autoremove --purge -y unzip alien gcc-multilib  && chmod +x /labview.sh /entrypoint.sh
 ---> Running in d7dda7b38e00
container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
```
Maybe you can take a look.

**Comment by lenartj** [comment]
I can't reproduce this one. I've just built a container from the repo with no changes - docker 17.05.0-ce. Are you building on linux?

**Comment by fromarcanum** [comment]
I have an error too:

toa_kopaka@WorkStation ~/labview $ docker run --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix lenart/labview
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.26/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

Im a newbuy in a docker. When docker unpacked archives, it wrote some errors in the console:

Unpacking labview61-rt (6.1-2) ...
Setting up labview61-rt (6.1-2) ...
Warning: Skipping conversion of scripts in package labview61-rte: postinst postrm
Warning: Use the --scripts parameter to include the scripts.

Unpacking labview61-vxi (6.1-2) ...
Setting up labview61-vxi (6.1-2) ...
Warning: Skipping conversion of scripts in package nicvirte: postinst postrm
Warning: Use the --scripts parameter to include the scripts.
	dpkg --no-force-overwrite -i nicvirte_5.0.1-3_amd64.deb

And so one. I need to rebuild with a parameter "--scripts"?
Linux Mint 18 x64

**Comment by lenartj** [comment]
It looks like your user lacks access privilege to the docker daemon. Try `sudo adduser toa_kopaka docker`, login again, and re run the `docker run ...` command. Alternatively try `sudo docker run ...`

**Comment by fromarcanum** [comment]
Unfortunately, it didnt help.

I added user by the adduser, but i see only:

~ $ docker run --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix lenart/labview
adduser: The UID 0 is already in use.

And if i'll use a sudo, ill see the same.
